import React from 'react';

export const styles: { [key: string]: React.CSSProperties } = {
    authContainer: { display: 'flex', alignItems: 'center', justifyContent: 'center', minHeight: '100vh', padding: '1rem', background: 'linear-gradient(135deg, #343A40 0%, #212529 100%)' },
    authBox: { width: '100%', maxWidth: '400px', padding: '2.5rem', backgroundColor: 'var(--white)', color: '#343A40', borderRadius: '12px', boxShadow: '0 10px 25px rgba(0,0,0,0.1)' },
    header: { textAlign: 'center' as const, marginBottom: '1.5rem' },
    title: { color: 'var(--primary-color)', margin: '0 0 0.5rem 0', fontWeight: 700 },
    form: { display: 'flex', flexDirection: 'column' as const },
    formActions: { display: 'flex', justifyContent: 'center', gap: '1rem', marginTop: '2rem' },
    floatingActions: {
        position: 'fixed' as const,
        bottom: '2rem',
        right: '2rem',
        zIndex: 1050,
        display: 'flex',
        gap: '1rem',
        alignItems: 'center',
    },
    floatingSaveButton: {
        width: '60px',
        height: '60px',
        borderRadius: '50%',
        padding: 0,
        fontSize: '1.5rem',
        boxShadow: '0 4px 12px rgba(0,0,0,0.25)',
    },
    label: { marginBottom: '0.5rem', fontWeight: 500, fontSize: '0.9rem', color: '#495057'},
    toggleAuth: { marginTop: '1.5rem', textAlign: 'center' as const, fontSize: '0.9rem' },
    link: { color: 'var(--primary-color)', fontWeight: 600, cursor: 'pointer' },
    error: { color: 'var(--error-color)', backgroundColor: 'var(--error-bg)', padding: '12px', borderRadius: '6px', marginBottom: '1rem', textAlign: 'center' as const, fontSize: '0.9rem', border: '1px solid var(--error-color)' },
    dashboardLayout: { display: 'flex', minHeight: '100vh', position: 'relative' },
    sidebar: { width: '250px', backgroundColor: 'var(--surface-color)', padding: '1.5rem', display: 'flex', flexDirection: 'column' as const, borderRight: '1px solid var(--border-color)', transition: 'transform 0.3s ease-in-out', position: 'fixed', top: 0, left: 0, height: '100vh', zIndex: 1100 },
    sidebarHidden: { transform: 'translateX(-100%)' },
    sidebarHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '2rem' },
    sidebarToggleButton: { background: 'none', border: '1px solid var(--border-color)', color: 'var(--text-light)', cursor: 'pointer', padding: '6px', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', transition: 'background-color 0.2s' },
    sidebarTitle: { color: 'var(--primary-color)', fontSize: '1.8rem', fontWeight: 700, textAlign: 'center' as const, margin: 0 },
    navItem: { display: 'flex', alignItems: 'center', gap: '0.75rem', padding: '0.8rem 1rem', borderRadius: '8px', marginBottom: '0.5rem', cursor: 'pointer', transition: 'background-color 0.2s, color 0.2s', fontWeight: 500, color: 'var(--text-color)' },
    mainContent: { flex: 1, padding: '2rem 3rem', overflowY: 'auto' as const, transition: 'margin-left 0.3s ease-in-out' },
    mainContentMobile: { marginLeft: 0, padding: '1.5rem' },
    mainContentDesktop: { marginLeft: '250px' },
    pageHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '2rem', borderBottom: '1px solid var(--border-color)', paddingBottom: '1rem' },
    hamburger: { display: 'inline-block', background: 'none', border: 'none', cursor: 'pointer', padding: '0.5rem', color: 'var(--primary-color)' },
    tableContainer: { backgroundColor: 'var(--surface-color)', borderRadius: '8px', boxShadow: '0 4px 12px rgba(0,0,0,0.05)', overflow: 'hidden' },
    table: { width: '100%', borderCollapse: 'collapse' as const },
    th: { padding: '1rem', textAlign: 'left' as const, borderBottom: '2px solid var(--border-color)', backgroundColor: 'var(--surface-hover-color)', fontWeight: 600, color: 'var(--text-light)' },
    td: { padding: '1rem', borderBottom: '1px solid var(--border-color)' },
    actionButtons: { display: 'flex', gap: '0.5rem' },
    iconButton: { background: 'transparent', border: '1px solid transparent', color: 'var(--text-light)', padding: '6px', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer' },
    modalOverlay: { position: 'fixed' as const, top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(0, 0, 0, 0.6)', display: 'flex', alignItems: 'flex-start', justifyContent: 'center', zIndex: 1000, overflowY: 'auto' as const, padding: '4vh 1rem' },
    modalContent: { backgroundColor: 'var(--surface-color)', borderRadius: '12px', width: '90%', maxWidth: '550px', maxHeight: '90vh', display: 'flex', flexDirection: 'column' as const, boxShadow: '0 10px 25px rgba(0,0,0,0.1)', marginBottom: '2rem' },
    modalHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '1.5rem', borderBottom: '1px solid var(--border-color)' },
    modalTitle: { margin: 0, fontSize: '1.25rem', color: 'var(--primary-color)' },
    modalBody: { padding: '1.5rem', overflowY: 'auto' as const },
    modalFooter: { display: 'flex', justifyContent: 'flex-end', gap: '1rem', padding: '1.5rem', borderTop: '1px solid var(--border-color)', backgroundColor: 'var(--background-color)', borderBottomLeftRadius: '12px', borderBottomRightRadius: '12px' },
    clientCard: { backgroundColor: 'var(--surface-color)', borderRadius: '8px', padding: '1rem', marginBottom: '1rem', boxShadow: '0 2px 8px rgba(0,0,0,0.06)' },
    logItem: { borderBottom: '1px solid var(--border-color)', paddingBottom: '1rem', marginBottom: '1rem', display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' },
    detailCard: { backgroundColor: 'var(--surface-color)', borderRadius: '8px', boxShadow: '0 2px 8px rgba(0,0,0,0.06)', marginBottom: '1.5rem', overflow: 'hidden' },
    detailCardHeader: { padding: '1rem', backgroundColor: 'var(--surface-hover-color)', borderBottom: '1px solid var(--border-color)', display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
    detailCardTitle: { margin: 0, fontSize: '1rem', fontWeight: 600 },
    detailCardBody: { padding: '1rem', fontSize: '0.9rem' },
    detailGroup: { marginBottom: '0.75rem' },
    detailGroupTitle: { fontWeight: 600, fontSize: '0.8rem', color: 'var(--text-light)', marginBottom: '0.25rem' },
    clinicalDataValue: { fontSize: '1.1rem', fontWeight: 600, color: 'var(--text-color)' },
    dashboardGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '1.5rem', marginBottom: '2rem' },
    summaryCard: { backgroundColor: 'var(--surface-color)', padding: '1.5rem', borderRadius: '12px', boxShadow: '0 4px 12px rgba(0,0,0,0.05)', display: 'flex', flexDirection: 'column' as const, alignItems: 'center', textAlign: 'center' as const, transition: 'transform 0.2s, box-shadow 0.2s' },
    summaryCardIcon: { color: 'var(--primary-color)', marginBottom: '1rem' },
    summaryCardValue: { fontSize: '2.5rem', fontWeight: 700, color: 'var(--primary-color)', margin: 0 },
    summaryCardLabel: { fontSize: '0.9rem', color: 'var(--text-light)', margin: '0.25rem 0 0 0' },
    quickActions: { marginBottom: '2rem', display: 'flex', gap: '1rem' },
    dashboardColumns: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '2rem' },
    dashboardColumnsMobile: { gridTemplateColumns: '1fr' },
    infoCard: { backgroundColor: 'var(--surface-color)', borderRadius: '12px', boxShadow: '0 4px 12px rgba(0,0,0,0.05)', overflow: 'hidden' },
    infoCardHeader: { padding: '1rem 1.5rem', borderBottom: '1px solid var(--border-color)', backgroundColor: 'var(--surface-hover-color)' },
    infoCardBody: { padding: '1.5rem' },
    activityList: { listStyle: 'none', padding: 0, margin: 0 },
    activityItem: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '0.75rem 0', borderBottom: '1px solid var(--border-color)' },
    activityItemLink: { color: 'var(--primary-color)', fontWeight: 600, cursor: 'pointer', textDecoration: 'none' },
    planStatus: { display: 'flex', alignItems: 'center', gap: '8px', fontWeight: 500 },
    statusDot: { width: '10px', height: '10px', borderRadius: '50%' },
    planDurationButtons: { display: 'flex', flexWrap: 'wrap', gap: '0.5rem', marginBottom: '1.25rem' },
    filterBar: { display: 'flex', gap: '1rem', marginBottom: '1.5rem', alignItems: 'center', flexWrap: 'wrap' as const },
    searchInputContainer: { position: 'relative', flex: 1, minWidth: '250px' },
    searchInput: { paddingLeft: '2.5rem', width: '100%', margin: 0 },
    searchInputIcon: { position: 'absolute' as const, top: '50%', left: '1rem', transform: 'translateY(-50%)', color: 'var(--text-light)' },
    filterButtonGroup: { display: 'flex', gap: '0.5rem' },
    profileDropdownContainer: { position: 'relative', display: 'inline-block' },
    profileDropdownButton: {
        display: 'flex',
        alignItems: 'center',
        gap: '0.75rem',
        padding: '0.5rem 0.5rem 0.5rem 1rem',
        backgroundColor: 'var(--surface-color)',
        borderRadius: '50px',
        color: 'var(--text-color)',
        border: '1px solid var(--border-color)',
        cursor: 'pointer',
        transition: 'background-color 0.2s, border-color 0.2s',
        minWidth: '180px',
        justifyContent: 'space-between'
    },
    profileDropdownMenu: {
        position: 'absolute',
        top: '120%',
        right: 0,
        backgroundColor: 'var(--surface-color)',
        borderRadius: '8px',
        boxShadow: '0 8px 20px rgba(0,0,0,0.25)',
        border: '1px solid var(--border-color)',
        minWidth: '220px',
        zIndex: 1200,
        overflow: 'hidden'
    },
    profileDropdownItem: {
        display: 'flex',
        alignItems: 'center',
        gap: '0.75rem',
        padding: '0.8rem 1rem',
        cursor: 'pointer',
        transition: 'background-color 0.2s, color 0.2s',
        color: 'var(--text-light)',
        fontSize: '0.9rem',
        border: 'none',
        background: 'none',
        width: '100%',
        textAlign: 'left' as const,
    },
    // Patient Portal Styles - Reworked for sidebar
    patientPortalLayout: { display: 'flex', minHeight: '100vh', position: 'relative' },
    patientPortalHeader: { padding: '1rem 2rem', backgroundColor: 'var(--surface-color)', borderBottom: '1px solid var(--border-color)', display: 'flex', justifyContent: 'space-between', alignItems: 'center', boxShadow: '0 2px 4px rgba(0,0,0,0.1)', flexShrink: 0 },
    patientPortalMain: { flex: 1, transition: 'margin-left 0.3s ease-in-out', overflow: 'auto', minWidth: 0 },
    patientSidebar: { width: '220px', backgroundColor: 'var(--surface-color)', padding: '1.5rem', display: 'flex', flexDirection: 'column' as const, borderRight: '1px solid var(--border-color)', transition: 'transform 0.3s ease-in-out', position: 'fixed', top: 0, left: 0, height: '100vh', zIndex: 1100 },
    patientContent: { padding: '2rem 3rem' },
    patientContentMobile: { padding: '1.5rem' },
    patientNavItem: { display: 'flex', alignItems: 'center', gap: '0.75rem', padding: '0.8rem 1rem', borderRadius: '8px', marginBottom: '0.5rem', cursor: 'pointer', transition: 'background-color 0.2s, color 0.2s', fontWeight: 500, border: 'none', background: 'transparent', width: '100%', textAlign: 'left' as const },
};